[build]
command = "npm run build"
publish = "dist"

[build.environment]
VITE_AUTH0_DOMAIN = ""
VITE_AUTH0_AUDIENCE = ""
VITE_AUTH0_CLIENT_ID = ""
SECRETS_SCAN_OMIT_KEYS = "VITE_AUTH0_DOMAIN,VITE_AUTH0_AUDIENCE,VITE_AUTH0_CLIENT_ID,VITE_API_URL"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
