[build]
  # The command Netlify runs to build your app
  command = "npm run build"

  # Folder that contains the production-ready build
  publish = "dist"

  # (Optional) Non-sensitive defaults — you can override these from Netlify UI if needed
  [build.environment]
    VITE_AUTH0_DOMAIN = "dev-7whr3yiydc13aogp.eu.auth0.com"
    VITE_AUTH0_AUDIENCE = "https://recipes-api"
    VITE_AUTH0_CLIENT_ID = "dgzwTiXahFJjvtapPW9ASvSymz8qdMIT"
    VITE_API_URL = "https://<your-backend-api>.netlify.app"

# Redirect rule for client-side routing (important for React Router / Vite)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
